config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  get "/users/:id", to: "application#custom", as: :user_id
  resources :costumes do
    resources :rents, only: [:create, :new, :destroy]
  end
  resources :rents, only: [:destroy, :update, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/costume.rb
class Costume < ApplicationRecord
  belongs_to :user
  has_many :rents, dependent: :destroy
  has_many_attached :photos
  validates :name, :description, :price, :city, presence: true
  validates :size, inclusion: { in: %w(XS S L XL XXL)}
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
  include PgSearch::Model
  pg_search_scope :global_search,
  against: [ :name, :description, :city ],
  using: {
    tsearch: { prefix: true }
  }


end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :costume
  validates :end_date, :begin_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :costumes, dependent: :destroy
  has_many :rents, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  def custom
    @user = User.find(params[:id])
    @costumes = @user.costumes
  end
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  def index
    @costumes = Costume.all
    # if params[:query].present?
    #   query_search = "name OR description OR city ILIKE ?"
    #   @costumes = @costumes.where(query_search,query: "%#{params[:query]}")
    # end
    @markers = @costumes.geocoded.map do |costume|
      {
        lat: costume.latitude,
        lng: costume.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {costume: costume})
      }
    end

    if params[:query].present?
    @costumes = @costumes.where(title: params[:query])
    end

  end

  def show
    @costume = Costume.find(params[:id])
    @marker = { lat: @costume.latitude, lng: @costume.longitude, info_window_html: render_to_string(partial: "info_window", locals: {costume: @costume})}
  end

  def new
    @costume = Costume.new
  end

  def edit
    @costume = Costume.find(params[:id])
  end

  def create
    @costume = Costume.new(costume_params)
    @costume.user_id = current_user.id
    @costume.save!
    redirect_to costume_path(@costume)
  end

  def update
    @costume = Costume.find(params[:id])
    @costume.update(costume_params)
    redirect_to costume_path(@costume)
  end

  def destroy
    @costume= Costume.find(params[:id])
    # @rents = @costume.rents
    # @rents.destroy
    @costume.destroy
    redirect_to costumes_path, status: :see_other
  end

  private

  def costume_params
    params.require(:costume).permit(:name, :description, :price, :size, :city, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @costumes = Costume.all
    if params[:query].present?
      @costumes = Costume.global_search(params[:query])
    end
  end

  def profile
    @rents = current_user.rents
    @costumes = current_user.costumes
  end

  def destroy
    @rent = Rent.find(params[:id])
    @rent.destroy
    redirect_to profile_path, status: :see_other
  end

  def edit
    @rent = Rent.find(params[:id])
  end
  # def params_rent
  #   params.require(:costume).permit(:rent_id, :id)
  # end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def new
    @costume = Costume.find(params[:costume_id])
    @rent = Rent.new
  end

  def create
    @costume = Costume.find(params[:costume_id])
    @rent = Rent.new(rent_params)
    @rent.user = current_user
    @rent.costume = @costume
    if @rent.save!
      flash[:notice] = "Rent successfully created"
      redirect_to profile_path(current_user)
    else
      redirect_to new_costume_rent_path(@costume)
    end
  end

  def destroy
    @rent = Rent.find(params[:id])
    @rent.destroy
    redirect_to profile_path, status: :see_other
  end

  def edit
    @rent = Rent.find(params[:id])
    @costume = @rent.costume.id
  end

  def update
    @rent = Rent.find(params[:id])
    @rent.update(rent_params)
    redirect_to profile_path
  end

  private

  def rent_params
    params.require(:rent).permit(:begin_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/custom.html.erb
<div class="complete">
  <div class="bar">
        <div class="centered-text">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "user-pic" %>
          <h2>Costumes by</h2>
          <p> <%= @user.email %></p>
        </div>
  </div>  <!-- bar -->

    <div class="cos">
      <div class="my-cos">
        <h2>Costumes in rent</h2>
        <div class="cos-card-my">
          <% @costumes.first(10).each do |costume|%>
            <div class="cos-method">
              <%=link_to costume_path(costume) do  %>
                <%= cl_image_tag costume.photos.first.key, width: 210, height:200,crop: :fill, class: "rounded-borders"%>
              <% end %>
              <h5><%= costume.name %></h5>
            </div> <!-- cos-method -->
          <% end %>
        </div>
      </div> <!-- my-cos -->
    </div>
  </div>
</div>

app/views/costumes/_info_window.html.erb
<h2><%= costume.name %></h2>
<p><%= costume.city %></p>

app/views/costumes/edit.html.erb
<h1>Modify your Costume offer</h1>
<div class="container3">
  <div class="form_container">
  <div class="image-form">
<% @costume.photos.each do |photo| %>
<%= cl_image_tag photo.key, width: 350, crop: :fill %>
</div>
<% end %>
<%= simple_form_for @costume do |f| %>
  <%= f.input :name %>
  <%= f.input  :description%>
  <%= f.input :size, :collection => %w[XS S L XL XXL] %>
  <%= f.input  :city%>
  <%= f.input :price %>
  <%= f.submit 'Edit my costume', :class => 'btn btn-ghost' %>
<% end %>
<%= link_to "Back to Costume", costume_path(@costume), :class => "btn btn-ghost"  %>
 </div>
</div>

app/views/costumes/index.html.erb
<h1 class="indextitle"><strong>Every Costume YOU'll ever need !</strong></h1>
<div class="mappy" style="width: 90%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<div class="container2">
   <% @costumes.each do |costume| %>
      <div class="cards__index">

            <% if costume.photos.attached? %>
              <%= cl_image_tag costume.photos.first.key, class: "card-image"%>
            <% end %>
              <div class="card__home">
                <div class="descriname">
                  <h2><%= link_to costume.name, costume_path(costume) %></h2>
                  <p> <%= costume.description %> </p>
                </div>
                <div class="avaprice">
                  <h3 class="card-pricing">Price: <%= costume.price %> €/day</h3>
                  <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-user avatar-bordered" />
              </div>
            </div>
        </div>
      <% end %>
</div>

app/views/costumes/new.html.erb
<h1>Create your costume offer</h1>
<div class="container3">
  <div class="form_container">
  <%= simple_form_for @costume do |f| %>
    <%= f.input :name %>
    <%= f.input :description%>
    <%= f.input :size, :collection => %w[XS S M L XL XXL] %>
    <%= f.input :city%>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit 'Create costume', :class => 'btn btn-ghost' %>
  <% end %>
  <%= link_to "Back", root_path(@costume), :class => "btn btn-ghost"  %>
  </div>
</div>

app/views/costumes/show.html.erb
<div class="container_show d-flex">
  <div class="card-trip">
          <div class="costume">
            <%  @costume.photos.each do |photo| %>
            <%= cl_image_tag photo.key, width: 400 %>
            <% end %>
          </div>
          <div class="d-flex justify-content-center">
              <%= link_to "Profile", user_id_path(@costume.user), :class => "btn btn-ghost"  %>
              <%= link_to "Rent", new_costume_rent_path(@costume), :class => "btn btn-ghost"   %>
              <%= link_to "Delete",
                    costume_path(@costume), :class => "btn btn-ghost",
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
                    <%= link_to "Back", costumes_path, :class => "btn btn-ghost"   %>
          </div>
        <div class="card-costume">
            <div>
              <h2><strong><%= @costume.name  %></strong></h2>
              <p><strong>Description: </strong> <%= @costume.description  %></p>
              <p><strong>City: </strong><%= @costume.city  %></p> <p><strong>Size: </strong><%= @costume.size  %></p>
            </div>
            <div class="avaprice">
                <h2 class="card-trip-pricing"><%= @costume.price  %>€/Day</h2>
                <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered"/>
            </div>
        </div>
    </div>
    <div class="map" style="width: 100%; height: 948px;"
      data-controller="map2"
      data-map2-marker-value="<%= @marker.to_json %>"
      data-map2-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>
  <%#
  <div class="container d-flex">
  <div class="row align-items-start">
    <% pics = @costume.photos %>
    <%# <% pics.each do |photo| %>
      <%# <% <div class="col"> %>
          <%# <%= @costume.photo  %>
          <%# </div> %>
    <%# <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CostumeBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.bayonne.fr/fileadmin/_processed_/3/d/csm_Bayonne-_F%C3%AAtes_et_costumes__4__85ecaff821.jpg);">
  <div class="titres">
    <h1>Costumes BNB</h1>
    <p>Costumes BNB, THE website to rent a cool costume.</p>
  </div>
</div>
    <div class="search d-flex justify-content-between">
<%= link_to "Create your costume offer", new_costume_path, :class => "btn btn-ghost" %>
       <div class="search-placement">
        <%= simple_form_for :search, url: root_path, method: :get do |f| %>
        <div class="search-form-control form-group">
            <input class="form-control string required" type="text" name="query" id="" />
            <% end %>
            <button type="submit" class="btn btn-flat">
              <i class="fas fa-search"></i> Search
            </button>
          </div>
        </div>
      </div>
<div class="container2">
   <% @costumes.first(16).each do |costume| %>
       <div class="cards__index">
          <%= cl_image_tag costume.photos.first.key, crop: :pad,class: "card-image" %>
            <div class="card__home">
              <div class="descriname">
                  <h2><%= link_to costume.name, costume_path(costume) %></h2>
                  <p> <%= costume.description %> </p>
                </div>
              <div class="avaprice">
                <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-user avatar-bordered" />
                <h2 class="card-pricing">Price: <%= costume.price %> €/day</h2>
              </div>
            </div>
        </div>
    <% end %>
</div>
<%= link_to "All the costumes", costumes_path, :class => "btn btn-ghost"  %>

app/views/pages/profile.html.erb
<div class="complete">
  <div class="bar">
    <div class="centered-text">
      <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "user-pic" %>
      <h2>Your profile</h2>
      <p>Hello <%= current_user.email %>!</p>
    </div>
  </div>  <!-- bar -->

  <div class="cos">
      <div class="rented-cos">
          <h2>Your rented costumes</h2>
        <div class="cos-card-rent">
          <% @rents.each do |rent| %>
            <div class="cos-method">
              <% rent.costume.photos.each do |photo| %>
                <% @rented_costume = rent.costume %>
                <% if @rented_costume.photos.attached? %>
                  <%=link_to costume_path(rent.costume) do  %>
                  <div class="cos-image">
                    <%= cl_image_tag photo.key, width: 210, height:200, crop: :fill, class: "rounded-borders"%>
                  </div> <!-- "cos-image" -->
                <% end %>
               	<h5 ><%= rent.costume.name %></h5>
                <p>Du <%=rent.begin_date%></p>
                <p>Au <%=rent.end_date%></p>
                <% end %>
                <%= link_to "Edit", edit_rent_path(rent), class: 'btn btn-ghost' %>
                <%= link_to "Delete", rent, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-ghost' %>
              <% end %>
            </div> <!-- "cos-image" -->
          <% end %>
        </div> <!-- classless -->
      <div class="my-cos">
          <h2>Your costumes</h2>
        <div class="cos-card-my">
              <% current_user.costumes.each do |costume| %>
                <div class="cos-method">
                  <%=link_to costume_path(costume) do  %>
                    <%= cl_image_tag costume.photos.first.key, width: 210, height:200,crop: :fill, class: "rounded-borders"%>
                  <% end %>
                  <h5><%= costume.name %></h5>
                  <%= link_to "Edit", edit_costume_path(costume), class: 'btn btn-ghost' %>
                </div> <!-- cos-method -->
              <% end %>
        </div>
      </div> <!-- my-cos -->
      </div> <!-- rented-cos -->
  </div> <!-- cos -->
</div> <!-- complete -->

                <%# <%= link_to "Edit", edit_costume_rent_path(rent), class: 'btn btn-ghost' %>

app/views/rents/edit.html.erb
<h1>Modify your costume rent date</h1>
<div class="container3">
  <div class="form_container">
  <div class="image-form">
<% @rent.costume.photos.each do |photo| %>
<%= cl_image_tag photo.key, width: 350, crop: :fill %>
</div>
<% end %>
<%= simple_form_for(@rent) do |f| %>
  <%= f.input :begin_date %>
  <%= f.input :end_date%>
  <%= f.submit "Edit Rent", :class => "btn btn-ghost btn-form" %>

<% end %>
<%= link_to "Back to Costume", profile_path, :class => "btn btn-ghost"  %>
 </div>
</div>

app/views/rents/new.html.erb
<div class="container_form">
  <div class="edit_center">
    <div class="costume">
        <h2><strong>Rent for <%= @costume.name %></strong></h2>
        <%  @costume.photos.each do |photo|  %>
          <%= cl_image_tag photo.key, width: 400, height: 600, crop: :fit %>
        <% end %>
    </div>
        <div class="card_edit">
            <p><%= @costume.description %></p>
            <p>  <strong>Get your Costume for : <%= @costume.price %>€/day</strong> </p>
        </div>
  </div>
        <div class="form_container">
          <h2 class="h2rent"><strong>Because with BNB Costumes...</strong></h2>
          <div class="img_center">
            <p id="logo" ><%= image_tag "logo.png", width: 450, height: 350%></p>
          </div>
          <p>...it's the easiest and fastest way to get your Costume in time!</p>
              <%= simple_form_for [@costume,@rent] do |f| %>
                <%= f.input :begin_date %>
                <%= f.input :end_date%>
                <%= f.submit "Rent Costume", :class => "btn btn-ghost btn-form" %>
                <% end %>
        </div>
</div>
<%# <div class="card">
<% price_in_days = (@rent.end_date - @rent.begin_date).to_i %>
<%# <% price = @costume.price * price_in_days %>
<%# <%= "You rent for #{price_in_days} days, cost #{price}"  %>
<%# </div> %>
<%= link_to "Back", costume_path(@costume), :class => "btn btn-ghost" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Costumes BNB is made with <i class="fas fa-heart"></i>!
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
      Costumes BNB
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All costumes", costumes_path, class: "nav-link" %>
          </li>



          <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "My rents", profile_path, class: "dropdown-item" %>
              <%= link_to "Create your costume offer", new_costume_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>